amazonProperties:
    endpointUrl: https://s3.sa-east-1.amazonaws.com
    accessKey: AKIAX2K6IMK7DAIQ6TDG
    secretKey: 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
    bucketName: alkemy-ong
    region: sa-east-1